### ISSUE TITLE
Package depends on Evil and Flycheck

### ISSUE THREAD

**Issue by gcentauri** [lbolla/emacs-quasi-monochrome#2]
not a major issue, but i was quite surprised when installing this theme that the Evil package was installed as well. I'm pretty sure there's ways to make the styling conditional on if a package or function is defined. `fboundp` for example can check if a symbol has a definition.

I may get some time to work on this myself, but wanted to raise an issue in the meantime. Thanks for the theme!

**Comment by lbolla** [comment]
Thanks for reporting it! I've removed requirements to `evil` and `flycheck`.
